services:
  https-portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - fess01
    environment:
      DOMAINS: 'docsearch.codelibs.org -> http://fess01:8080'
      STAGE: local
      CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
          add_header X-Frame-Options SAMEORIGIN;
    networks:
      - docsearch_net
    volumes:
      - ./data/https-portal/ssl_certs:/var/lib/https-portal
      - ./data/https-portal/conf/docsearch.codelibs.org.ssl.conf.erb:/var/lib/nginx-conf/docsearch.codelibs.org.ssl.conf.erb:ro

  fess01:
    image: ghcr.io/codelibs/fess:14.4.0
    container_name: fess01
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - es01
    environment:
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
      - "FESS_JAVA_OPTS=-Dfess.config.crawler.document.cache.enabled=false -Dfess.config.adaptive.load.control=20 -Dfess.config.query.facet.fields=label,host"
    networks:
      - docsearch_net
    volumes:
      - ./data/fess/opt/fess:/opt/fess
      - ./data/fess/var/lib/fess:/var/lib/fess
      - ./data/fess/var/log/fess:/var/log/fess
      - ./data/fess/usr/share/fess/app/WEB-INF/plugin:/usr/share/fess/app/WEB-INF/plugin
      - ./data/fess/usr/share/fess/app/WEB-INF/view/docsearch:/usr/share/fess/app/WEB-INF/view/docsearch
      - ./data/fess/usr/share/fess/app/css/docsearch:/usr/share/fess/app/css/docsearch
      - ./data/fess/usr/share/fess/app/images/docsearch:/usr/share/fess/app/images/docsearch

  es01:
    image: ghcr.io/codelibs/fess-elasticsearch:7.17.6
    container_name: es01
    restart: always
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/usr/share/elasticsearch/config/dictionary:/usr/share/elasticsearch/config/dictionary
    ports:
      - 9200:9200
    networks:
      - docsearch_net

networks:
  docsearch_net:
    driver: bridge
